// Shared design tokens for every page. See DESIGN.md for the rationale.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbcb",
        "secondary": "#c2c1ff",
        "tertiary": "#ffb691",
        "surface-container-lowest": "#010f1f",
        "outline": "#8b91a0",
        "primary": "#aac7ff",
        "surface-container": "#122131",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb691",
        "secondary-fixed-dim": "#c2c1ff",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-container": "#4a1b00",
        "on-secondary-fixed-variant": "#332dbc",
        "on-primary-fixed": "#001b3e",
        "on-background": "#d4e4fa",
        "on-primary": "#003064",
        "secondary-container": "#3630bf",
        "on-primary-container": "#002957",
        "inverse-surface": "#d4e4fa",
        "surface-tint": "#aac7ff",
        "on-secondary": "#1800a7",
        "on-error": "#690005",
        "primary-fixed-dim": "#aac7ff",
        "inverse-on-surface": "#233143",
        "on-surface": "#d4e4fa",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#00468d",
        "outline-variant": "#414754",
        "background": "#051424",
        "surface": "#051424",
        "surface-container-high": "#1c2b3c",
        "surface-bright": "#2c3a4c",
        "on-tertiary": "#552000",
        "secondary-fixed": "#e2dfff",
        "on-secondary-fixed": "#0c006b",
        "on-tertiary-fixed-variant": "#793100",
        "primary-fixed": "#d6e3ff",
        "surface-dim": "#051424",
        "error-container": "#93000a",
        "surface-variant": "#273647",
        "inverse-primary": "#005db8",
        "surface-container-low": "#0d1c2d",
        "on-surface-variant": "#c0c6d6",
        "primary-container": "#3e90ff",
        "surface-container-highest": "#273647",
        "tertiary-container": "#eb6a12",
        "on-secondary-container": "#b1b1ff",
        "success-container": "#005335",
        "on-success-container": "#8bf8b8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "max-width": "1440px",
        "gutter": "16px",
        "margin-desktop": "32px",
        "unit": "4px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "code-md": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-xl": ["Geist"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
};
